### ISSUE TITLE
Mutil-gpu training and the STTN+OVD's net structure in the paper

### ISSUE THREAD

**Issue by zrongcheng** [alpErenSari/spatioTemporalTransformer#1]
1. The code did not support mutil-gpu.
2. The repo seems not the best result in the paper.

**Comment by alpErenSari** [comment]
Hi, 
1) Unfortunately currently this code does not support multi-gpu since I only have one GPU and can't test it. Sorry about it. 
2) Apparently, this code is not complete and needs fine tunings. Unfortunately, I'm not able to do this since I do not have enough time for this. I'll deeply appreciate any effort about this.
